// self invoked excution function
(function(x){console.log(x)})(30)
// try catch
try {
    console.log(hh)
} catch (error) {
    console.error(error)
}
console.log("ef")